export type FieldKind =
  | "text"
  | "longText"
  | "number"
  | "date"
  | "single"
  | "multi"
  | "linked"
  | "attachment"
  | "system";

export interface FieldDefinition {
  name: string;
  kind: FieldKind;
  /** Allowed values for single and multi select fields. */
  options?: readonly string[];
}

/**
 * Field catalog from UnifiedEventsSchema (the source of truth for field names, kinds and
 * allowed values). Names are kept exactly as defined there, including its spellings
 * (e.g. TURBT_Surgeion_Notes, Imaging_Response_Critera).
 */
export const eventFieldCatalog: Record<string, FieldDefinition> = {
  Event_ID: { name: "Event_ID", kind: "system" },
  Event_UID: { name: "Event_UID", kind: "text" },
  Event_Date: { name: "Event_Date", kind: "date" },
  Event_Created_At: { name: "Event_Created_At", kind: "system" },
  Event_Source: { name: "Event_Source", kind: "single", options: [
      "Patient",
      "Clinician",
      "Document",
      "Imaging Center",
      "Lab",
      "Other",
    ] },
  Event_Related_UID: { name: "Event_Related_UID", kind: "text" },
  Event_Relationship: { name: "Event_Relationship", kind: "single", options: [
      "Produced_By",
      "Triggered_By",
      "Assessed_By",
      "Derived_From",
      "Related_To",
    ] },
  Event_Type: { name: "Event_Type", kind: "single", options: [
      "Diagnosis",
      "TURBT",
      "Pathology",
      "Cytology",
      "Lab",
      "Imaging",
      "Imaging_Response",
      "Cystoscopy",
      "Cystoscopy_Biopsy",
      "Somatic",
      "Germline",
      "ctDNA",
      "utDNA",
      "Treatment_Start",
      "Treatment_Delivery",
      "Treatment_Change",
      "Treatment_Response",
      "Recurrence",
      "Progression",
      "QoL",
      "Symptom",
      "Decision",
      "Note",
    ] },
  Event_Summary: { name: "Event_Summary", kind: "text" },
  Event_Details: { name: "Event_Details", kind: "longText" },
  Event_Measure_Type: { name: "Event_Measure_Type", kind: "single", options: [
      "Tumor size",
      "Lesion size",
      "Bladder wall thickness",
      "Creatinine",
      "PSA",
      "Hemoglobin",
      "WBC",
      "RBC/hpf",
      "AUA score",
      "ECOG",
      "Lymph node size",
      "Number of lesions",
      "Number of nodes",
      "Other",
    ] },
  Numeric_Value: { name: "Numeric_Value", kind: "number" },
  Numeric_Units: { name: "Numeric_Units", kind: "text" },
  Diagnosis_Histology: { name: "Diagnosis_Histology", kind: "single", options: [
      "Urothelial carcinoma",
      "Squamous cell carcinoma",
      "Adenocarcinoma",
      "Small cell carcinoma",
      "Other",
    ] },
  Diagnosis_Grade: { name: "Diagnosis_Grade", kind: "single", options: [
      "Low-grade",
      "High-grade",
      "Not graded/Not applicable",
      "Unknown",
    ] },
  Diagnosis_Variant_Histology: { name: "Diagnosis_Variant_Histology", kind: "multi", options: [
      "None",
      "Plasmacytoid",
      "Sarcomatoid",
      "Micropapillary",
      "Squamous differentiation",
      "Glandular differentiation",
      "Nested",
      "Small cell features",
      "Other",
    ] },
  Diagnosis_Initial_Presentation: { name: "Diagnosis_Initial_Presentation", kind: "longText" },
  T: { name: "T", kind: "single", options: [
      "Tis",
      "Ta",
      "T1",
      "T2",
      "T3",
      "T4",
    ] },
  N: { name: "N", kind: "single", options: [
      "N0",
      "N1",
      "N2",
      "N3",
      "NX",
    ] },
  M: { name: "M", kind: "single", options: [
      "M0",
      "M1",
    ] },
  Stage: { name: "Stage", kind: "single", options: [
      "Stage 0a",
      "Stage 0is",
      "Stage I",
      "Stage II",
      "Stage IIIA",
      "Stage IIIB",
      "Stage IVA",
      "Stage IVB",
    ] },
  TURBT_Completeness: { name: "TURBT_Completeness", kind: "single", options: [
      "Complete",
      "Incomplete",
    ] },
  TURBT_Surgeon_Notes: { name: "TURBT_Surgeon_Notes", kind: "longText" },
  TURBT_Specimen_Notes: { name: "TURBT_Specimen_Notes", kind: "longText" },
  Pathology_Histology: { name: "Pathology_Histology", kind: "single", options: [
      "Urothelial carcinoma",
      "Squamous cell carcinoma",
      "Adenocarcinoma",
      "Small cell carcinoma",
      "Other",
    ] },
  Pathology_Grade: { name: "Pathology_Grade", kind: "single", options: [
      "Low-grade",
      "High-grade",
      "Not graded/Not applicable",
      "Unknown",
    ] },
  Pathology_Variant_Histology: { name: "Pathology_Variant_Histology", kind: "multi", options: [
      "None",
      "Plasmacytoid",
      "Sarcomatoid",
      "Micropapillary",
      "Squamous differentiation",
      "Glandular differentiation",
      "Nested",
      "Small cell features",
      "Other",
    ] },
  Pathology_Depth: { name: "Pathology_Depth", kind: "single", options: [
      "Tis",
      "Ta",
      "T1",
      "T2",
      "T3",
      "T4",
    ] },
  Pathology_Margins: { name: "Pathology_Margins", kind: "single", options: [
      "Negative",
      "Positive",
      "Unknown",
    ] },
  Pathology_LVI: { name: "Pathology_LVI", kind: "single", options: [
      "Present",
      "Absent",
      "Unknown",
    ] },
  Pathology_Notes: { name: "Pathology_Notes", kind: "longText" },
  Cytology_Result: { name: "Cytology_Result", kind: "single", options: [
      "Negative",
      "Atypical",
      "Suspicious",
      "Positive",
      "Unsatisfactory",
      "Other",
    ] },
  Cytology_Category: { name: "Cytology_Category", kind: "single", options: [
      "Paris system",
      "Non-paris",
      "Unknown",
    ] },
  Cytology_Specimen: { name: "Cytology_Specimen", kind: "single", options: [
      "Voided urine",
      "Catherized urine",
      "Bladder wash",
      "Upper tract wash",
      "Other",
    ] },
  Cytology_Notes: { name: "Cytology_Notes", kind: "longText" },
  Lab_Flags: { name: "Lab_Flags", kind: "multi", options: [
      "WBC_low",
      "ANC_low",
      "Platelets_low",
      "Creatine_high",
      "eGFR_low",
      "AST_high",
      "ALT_high",
      "AlkPhos_high",
      "LDH_high",
      "CRP_high",
      "Albumin_low",
      "Glucose_high",
      "Other_abnormal_lab",
    ] },
  Lab_Values: { name: "Lab_Values", kind: "longText" },
  Lab_Significance_Reasons: { name: "Lab_Significance_Reasons", kind: "multi", options: [
      "Renal_function_compromise",
      "Immune_system_compromise",
      "Hepatic_toxicity",
      "Treatment_gating_concern",
      "Predictive_biomarker_change",
      "Hyperglycemia",
      "Unexpected_abnormality",
      "Requires_provider_followup",
    ] },
  Lab_Notes: { name: "Lab_Notes", kind: "longText" },
  Treatment_Name: { name: "Treatment_Name", kind: "single", options: [
      "EVP",
      "EV",
      "Pembrolizumab",
      "Nivolumab",
      "Gemcitabine",
      "Cisplatin",
      "Carboplatin",
      "Gem/Cis",
      "Gem/Carbo",
      "Other systemic therapy",
      "BCG",
      "BCG+Interferon",
      "Gemcitabine intravesical",
      "Docetaxel intravesical",
      "Gem/Docetaxel",
      "Mitomycin C",
      "Other intravesical therapy",
      "Radiation therapy",
      "Chemoradiation",
      "IMRT",
      "SBRT",
      "Proton therapy",
      "Other radiation",
      "TURBT",
      "Repeat TURBT",
      "cystectomy",
      "Partial cystectomy",
      "Lymph node dissection",
      "Growth factor support",
      "Steroid premedication",
      "Antiemetic regimen",
      "Other supportive care",
      "Other",
    ] },
  Treatment_Cycle: { name: "Treatment_Cycle", kind: "number" },
  Treatment_Intent: { name: "Treatment_Intent", kind: "single", options: [
      "Curative",
      "Bladder-preserving",
      "Palliative",
    ] },
  Treatment_Route: { name: "Treatment_Route", kind: "single", options: [
      "Intravenous",
      "Oral",
      "Intravesical",
      "Radiation",
      "Subcutaneous",
      "Intramuscular",
      "Topical",
      "Other",
      "Unknown",
    ] },
  Treatment_Regimen_Details: { name: "Treatment_Regimen_Details", kind: "longText" },
  Treatment_Dose: { name: "Treatment_Dose", kind: "number" },
  Treatment_Dose_Units: { name: "Treatment_Dose_Units", kind: "single", options: [
      "mg",
      "mg/kg",
      "mg/m2",
      "g",
      "units",
      "Gy",
      "cGy",
      "mCi",
      "mL",
      "Other",
      "Unknown",
    ] },
  Treatment_Delivery_Status: { name: "Treatment_Delivery_Status", kind: "single", options: [
      "Delivered as Planned",
      "Dose Reduced",
      "Dose Increased",
      "Partially Delivered",
      "Interrupted",
      "Delayed",
      "Held",
      "Not Completed",
      "Unknown",
    ] },
  Treatment_Delivery_Notes: { name: "Treatment_Delivery_Notes", kind: "longText" },
  Treatment_Change_Type: { name: "Treatment_Change_Type", kind: "single", options: [
      "Dose reduction",
      "Hold",
      "Resume",
      "Regimen change",
      "Treatment completed",
      "Other",
    ] },
  Treatment_Change_Reason: { name: "Treatment_Change_Reason", kind: "longText" },
  Treatment_Change_New_Regimen: { name: "Treatment_Change_New_Regimen", kind: "text" },
  Treatment_Change_Toxicity_Grade: { name: "Treatment_Change_Toxicity_Grade", kind: "number" },
  Treatment_Response_Category: { name: "Treatment_Response_Category", kind: "single", options: [
      "CR",
      "PR",
      "SD",
      "PD",
    ] },
  Treatment_Response_Modality: { name: "Treatment_Response_Modality", kind: "single", options: [
      "Imaging",
      "Clinical",
      "Cystoscopy",
      "Other",
    ] },
  Treatment_Response_Notes: { name: "Treatment_Response_Notes", kind: "longText" },
  Imaging_Modality: { name: "Imaging_Modality", kind: "single", options: [
      "CT",
      "MRI",
      "PET/CT",
      "Ultrasound",
      "Unknown",
    ] },
  Imaging_Result: { name: "Imaging_Result", kind: "longText" },
  Imaging_Region: { name: "Imaging_Region", kind: "single", options: [
      "Chest",
      "Abdomen",
      "Pelvis",
      "Abdomen/Pelvis",
      "Chest/Abdomen/Pelvis",
      "Whole Body",
      "Neck",
      "Brain",
      "Spine",
      "Head&Neck",
      "Upper Extremity",
      "Lower Extremity",
      "Lymph Nodes",
      "Other",
    ] },
  Imaging_ComparisonToPrior: { name: "Imaging_ComparisonToPrior", kind: "single", options: [
      "Improved",
      "Stable",
      "Worse",
      "New finding",
    ] },
  Imaging_Contrast: { name: "Imaging_Contrast", kind: "single", options: [
      "IV Contrast",
      "Oral Contrast",
      "IV and Oral Contrast",
      "With and Without Contrast",
      "No Contrast",
    ] },
  Imaging_Notes: { name: "Imaging_Notes", kind: "longText" },
  Imaging_Response_Category: { name: "Imaging_Response_Category", kind: "single", options: [
      "CR",
      "PR",
      "SD",
      "PD",
    ] },
  Imaging_Response_Critera: { name: "Imaging_Response_Critera", kind: "single", options: [
      "RECIST",
      "Lugano",
      "Other",
    ] },
  Imaging_Response_Target_Lesion_Change: { name: "Imaging_Response_Target_Lesion_Change", kind: "number" },
  Document_Attachment: { name: "Document_Attachment", kind: "attachment" },
  Document_Type: { name: "Document_Type", kind: "single", options: [
      "Pathology",
      "ImagingReport",
      "Consult Note",
      "Lab Report",
      "Other",
    ] },
  Document_Redaction_Status: { name: "Document_Redaction_Status", kind: "single", options: [
      "Redacted",
      "Contains PHI",
      "Unknown",
    ] },
  Symptom_Description: { name: "Symptom_Description", kind: "longText" },
  Symptom_Type: { name: "Symptom_Type", kind: "single", options: [
      "Peripheral neuropathy",
      "Dysgeusia",
      "Rash/skin irritation",
      "Alopecia",
      "Fatigue",
      "Nausea",
      "Vomiting",
      "Diarrhea",
      "Constipation",
      "Urinary frequency",
      "Urinary urgency",
      "Hematuria",
      "Pain",
      "Fever",
      "Weight loss",
      "Appetite loss",
      "Other",
    ] },
  Symptom_Severity: { name: "Symptom_Severity", kind: "number" },
  Symptom_Duration: { name: "Symptom_Duration", kind: "number" },
  Symptom_Duration_Units: { name: "Symptom_Duration_Units", kind: "single", options: [
      "minutes",
      "hours",
      "weeks",
      "months",
    ] },
  QoL_Physical: { name: "QoL_Physical", kind: "number" },
  Qol_Emotional: { name: "Qol_Emotional", kind: "number" },
  QoL_Urinary: { name: "QoL_Urinary", kind: "number" },
  QoL_Pain: { name: "QoL_Pain", kind: "number" },
  QoL_Fatigue: { name: "QoL_Fatigue", kind: "number" },
  Qol_Notes: { name: "Qol_Notes", kind: "longText" },
  Somatic_Vendor: { name: "Somatic_Vendor", kind: "single", options: [
      "Caris",
      "Tempus",
      "FoundationOne",
      "Veracyte",
      "Other",
    ] },
  Somatic_Test_Type: { name: "Somatic_Test_Type", kind: "single", options: [
      "DNA sequencing",
      "RNA sequencing",
      "Gene expression classifier",
      "Immunohistochemistry",
      "Other",
    ] },
  Somatic_Key_Findings: { name: "Somatic_Key_Findings", kind: "multi", options: [
      "ERBB2 overexpression",
      "ERBB2 amplification",
      "PD-L1 CPS",
      "FGFR3 mutation",
      "TMB High",
      "MSI-H",
      "MMR deficient",
      "Other",
    ] },
  Somatic_PD_L1_CPS: { name: "Somatic_PD_L1_CPS", kind: "number" },
  Somatic_ERBB2_Expression: { name: "Somatic_ERBB2_Expression", kind: "single", options: [
      "Negative",
      "Low",
      "Intermediate",
      "High",
      "Unknown",
      "Other",
    ] },
  Somatic_Notes: { name: "Somatic_Notes", kind: "longText" },
  Germline_Vendor: { name: "Germline_Vendor", kind: "single", options: [
      "Ambry",
      "Invitae",
      "Myriad",
      "Natera Renasight",
      "Tempus",
      "Other",
      "Unknown",
    ] },
  Germline_Findings: { name: "Germline_Findings", kind: "multi", options: [
      "CHEK2",
      "BRCA1",
      "BRCA2",
      "MLH1",
      "MSH2",
      "MSH6",
      "PMS2",
      "APC",
      "Other",
    ] },
  Germline_Pathogenicity: { name: "Germline_Pathogenicity", kind: "single", options: [
      "Pathogenic",
      "Likely pathogenic",
      "VUS",
      "Benign",
      "Unknown",
      "Other",
    ] },
  Germline_Notes: { name: "Germline_Notes", kind: "longText" },
  Decision_Type: { name: "Decision_Type", kind: "single", options: [
      "Elect bladder preservation",
      "Decline cystectomy",
      "Proceed with EVP",
      "Complete response confirmed",
      "Switch surveillance modality",
      "Change cystoscopy frequency",
      "Change imaging frequency",
      "Add ctDNA surveillance",
      "Add utDNA surveillance",
      "Hold treatment",
      "Resume treatment",
      "Refer to urology",
      "Refer to medical oncology",
      "Refer to radiation oncology",
      "Other",
    ] },
  Decision_Consensus: { name: "Decision_Consensus", kind: "single", options: [
      "Patient and clinician aligned",
      "Patient preference overrides clinician recommendation",
      "Clinician recommendation overrides patient preference",
      "Multidisciplinary consensus",
      "Unknown",
    ] },
  Decision_Physician_Recommendation: { name: "Decision_Physician_Recommendation", kind: "longText" },
  Decision_Patient_Preference: { name: "Decision_Patient_Preference", kind: "longText" },
  Decision_Notes: { name: "Decision_Notes", kind: "longText" },
  ctDNA_Vendor: { name: "ctDNA_Vendor", kind: "single", options: [
      "Signatera(Natera)",
      "xM NeXT Personal Dx(Tempus)",
      "Reveal(Guardant)",
      "Northstar Response(BillionToOne)",
      "Haystack MRD(Quest Diagnostics)",
    ] },
  ctDNA_Assay_Type: { name: "ctDNA_Assay_Type", kind: "single", options: [
      "Tumor-informed",
      "Tumor-naïve(tissue free)",
      "Unknown",
      "Other",
    ] },
  ctDNA_Value: { name: "ctDNA_Value", kind: "number" },
  ctDNA_Units: { name: "ctDNA_Units", kind: "single", options: [
      "MTM/ml",
      "MAF%",
      "Methylation signal",
      "Detected",
      "Not detected",
      "Other",
    ] },
  ctDNA_Trend: { name: "ctDNA_Trend", kind: "single", options: [
      "Rising",
      "Falling",
      "Stable",
      "Unknown",
    ] },
  utDNA_Vendor: { name: "utDNA_Vendor", kind: "single", options: [
      "UroAmp(Veracyte/Convergent Genomics)",
      "Natera(pipeline)",
      "Other",
      "Unknown",
    ] },
  utDNA_Assay_Type: { name: "utDNA_Assay_Type", kind: "single", options: [
      "Tumor-informed",
      "Tumor-naïve(tissue free)",
      "Unknown",
      "Other",
    ] },
  utDNA_Units: { name: "utDNA_Units", kind: "single", options: [
      "Mutation burden score",
      "Variant count",
      "Methylation signal",
      "Detected",
      "Not detected",
      "Other",
      "Unknown",
    ] },
  utDNA_Value: { name: "utDNA_Value", kind: "number" },
  utDNA_Trend: { name: "utDNA_Trend", kind: "single", options: [
      "Rising",
      "Falling",
      "Stable",
      "Unknown",
    ] },
  utDNA_Notes: { name: "utDNA_Notes", kind: "longText" },
  Cystoscopy_Findings: { name: "Cystoscopy_Findings", kind: "single", options: [
      "Normal",
      "Inflammation",
      "Papillary lesion",
      "Flat lesion",
      "Suspicious area",
      "Mass",
      "Ulceration",
      "Erythema",
      "Necrosis",
      "Other",
      "Unknown",
    ] },
  Cystoscopy_Biopsy_Taken: { name: "Cystoscopy_Biopsy_Taken", kind: "single", options: [
      "Yes",
      "No",
      "Not applicable",
      "Unknown",
    ] },
  Cystoscopy_Biopsy_Result: { name: "Cystoscopy_Biopsy_Result", kind: "single", options: [
      "Negative",
      "Atypia",
      "Dysplasia",
      "CIS",
      "Low-grade carcinoma",
      "High-grade carcinoma",
      "Invasive carcinoma",
      "Other",
      "Pending",
      "Unknown",
    ] },
  Cystoscopy_Biopsy_Site: { name: "Cystoscopy_Biopsy_Site", kind: "text" },
  Cystoscopy_Biopsy_Notes: { name: "Cystoscopy_Biopsy_Notes", kind: "longText" },
  Cystoscopy_Notes: { name: "Cystoscopy_Notes", kind: "longText" },
  Cystoscopy_Visibility: { name: "Cystoscopy_Visibility", kind: "single", options: [
      "Good",
      "Fair",
      "Poor",
      "Obstructed",
      "Unknown",
    ] },
  Cystoscopy_Reason: { name: "Cystoscopy_Reason", kind: "single", options: [
      "Routine surveillance",
      "Symptom-driven",
      "Follow-up abnormal imaging",
      "Follow-up cytology",
      "Other",
    ] },
  Recurrence_Location: { name: "Recurrence_Location", kind: "text" },
  Recurrence_Spread_Category: { name: "Recurrence_Spread_Category", kind: "single", options: [
      "Local",
      "Regional",
      "Metastatic",
      "Unknown",
    ] },
  Recurrence_Modality: { name: "Recurrence_Modality", kind: "single", options: [
      "Imaging",
      "Cystoscopy",
      "Cytology",
      "Molecular",
      "Other",
    ] },
  Recurrence_Confirmation: { name: "Recurrence_Confirmation", kind: "single", options: [
      "Imaging",
      "Biopsy",
      "Cytology",
      "Other",
    ] },
  Recurrence_Notes: { name: "Recurrence_Notes", kind: "longText" },
  Progression_Location: { name: "Progression_Location", kind: "text" },
  Progression_Stage_Spread: { name: "Progression_Stage_Spread", kind: "single", options: [
      "Local",
      "Regional",
      "Metastatic",
      "Unknown",
    ] },
  Progression_Modality: { name: "Progression_Modality", kind: "single", options: [
      "Imaging",
      "Cystoscopy",
      "Cytology",
      "Molecular",
      "Other",
    ] },
  Progression_Stage_Change: { name: "Progression_Stage_Change", kind: "text" },
  Progression_Notes: { name: "Progression_Notes", kind: "longText" },
};
