@host = http://localhost:3000

@accountId = recJqNj8jWjOWtdla
@masterId = recruNzM6KPFeCPel
@uid = EVP-F196-F62C


### Create Account
POST {{host}}/create-account
Content-Type: application/json

{
  "email": "unique-test-001@example.com",
  "firstName": "Test",
  "lastName": "User"
}

### Update Account
POST {{host}}/update-account
Content-Type: application/json

{
  "accountId": "{{accountId}}",
  "updates": {
    "FirstName": "Test",
    "LastName": "User",
    "Email": "unique-test-001@example.com"
  }
}

### Update Master
POST {{host}}/update-master
Content-Type: application/json

{
  "masterId": "{{masterId}}",
  "updates": {
    "ConsentVersion": "v1",
    "Notes": "Initial onboarding complete"
  }
}


